Fixing the AvgDistMat_ExpError validation script
revbayes/revbayes pull request #417
Opened 2023-12-05 15:31 UTC by davidcerny

Fixing the validation script for supertree analyses relying on the `fnAverageDistanceMatrix()` function and the `dnExponentialError()` distribution, in accordance with Sebastian's advice: `rBDP()` is used to generate random "true" trees without having them appear as stochastic nodes in the resulting model. The test now passes.

2024-03-28 12:06 UTC, hoehna requested changes

2024-03-28 12:06 UTC, hoehna commented on validation/scripts/Validation_AvgDistMat_ExpError.Rev
> +true_tree <- rBDP(n=1, lambda=speciation, mu=extinction, rootAge=tree_height, condition="nTaxa", taxa=species)
I find this slightly misleading as the simulated tree will actually not be used for the validation analysis. As you see later, only ADM will be used as a placeholder. During the validation analysis, we actually simulate new datasets from "dnExponentialError(distMat=mat, lambda=0.005)" and use this as the values for ADM in each replicate.

So my suggestion is to not simulate a tree here, rather use a fixed one, to avoid confusion. Or even better, clamp `exp_error_dist` to itself:
p_error_dist.clamp( p_error_dist )

2024-03-28 19:56 UTC, davidcerny commented on validation/scripts/Validation_AvgDistMat_ExpError.Rev
> +true_tree <- rBDP(n=1, lambda=speciation, mu=extinction, rootAge=tree_height, condition="nTaxa", taxa=species)
Hmm, I've made the requested change and the test still passes (i.e., the coverage frequencies are what they should be), so I guess that's good, but at this point I just don't understand how the validation tests are supposed to work. My understanding was that they try to implement the protocol of Talts et al. (2020), which should look like this:

$$
\tilde{\theta} \sim p(\theta) \hspace{3cm} (1)
$$

$$
\tilde{y} \sim f(y | \tilde{\theta}) \hspace{3cm} (2)
$$

$$
\theta \sim p(\theta | \tilde{y}) \hspace{3cm} (3)
$$

i.e., simulate a "true"value from the prior, simulate data conditional on that true value according to some sampling distribution $f$, then re-infer parameter values conditional on the simulated data, and exploit the fact that $\tilde{\theta} \sim p(\theta | \tilde{y})$. But what would $\tilde{\theta}$ correspond to in this modified script? We don't seem to be making a distinction between $\tilde{\theta}$ (simulated true value) and $\theta$ (re-inferred estimates), so how does the test just not fall apart conceptually?

2024-04-17 15:08 UTC, hoehna approved these changes
I'm happy about these modifications.

2024-04-17 16:46 UTC, merged