Optional precision in initial tree age checking
revbayes/revbayes pull request #455
Opened 2024-04-22 22:53 UTC by davidcerny

This PR is meant to provide a more lasting solution to issue #421. I have added a new argument called `ageCheckPrecision` to `dnBDSTP`, which determines how many decimal places should be used when comparing the tip ages of a user-specified initial tree to the ages (given either as ranges or fixed values) provided in a taxon data file. By default, the argument is set to 4. I have verified that the problem described in #421 does not resurface unless it is set to a value of 8 or greater.

We already have a test for using `dnBDSTP` with an initial tree, so I haven't added a new one. This would be a nice place to implement the idea that @bjoelle brought up on Slack a while ago, i.e., to have a test that's supposed to fail – that would help verify that it does in fact matter what value `ageCheckPrecision` is set to. However, as far as I know, we haven't figured out how to do that.

2024-04-23 07:07 UTC, bjoelle approved these changes
looks good to me
maybe as a test we can add the script from #421 ?

2024-04-23 13:36 UTC, hoehna requested changes

2024-04-23 13:36 UTC, hoehna commented on src/core/distributions/phylogenetics/tree/birthdeath/BirthDeathSamplingTreatmentProcess.h
> +                                                    const TypedDagNode<long> *age_check_precision);  //!< Constructor
Why is this a DAG node? DAG nodes should only be used if the intention is that the variable might change during an analysis.

2024-04-23 13:36 UTC, hoehna commented on src/core/utils/TreeUtilities.h
> +        Tree*                   startingTreeInitializer(Tree& treeToChange, std::vector<Taxon>& taxaToCopy, const long& agePrecision);  //!< make sure starting tree satisfies age constraints, and ass
doesn't need to be a `const long&` and instead can be `long` because a constant reference takes up as much space as a long.

2024-04-23 13:36 UTC, hoehna commented on src/revlanguage/distributions/phylogenetics/tree/Dist_BDSTP.cpp
> +        pr = static_cast<const Natural &>( age_check_precision->getRevObject() ).getDagNode();
Again, why as DAG node and not directly a value?

2024-04-23 13:36 UTC, hoehna commented on src/revlanguage/distributions/phylogenetics/tree/Dist_BDSTP.cpp
> +        dist_member_rules.push_back( new ArgumentRule( "ageCheckPrecision", Natural::getClassTypeSpec(), "If an initial tree is provided, how many decimal places should be used when checking its tip
I suggest to use `ArgumentRule::BY_VALUE`

2024-04-24 00:55 UTC, davidcerny commented
Made the changes requested by @hoehna, added a test as suggested by @bjoelle, and as a bonus, made it possible to use `Phi` as an alias of `rho` in `dnFBDP`.

2024-04-24 06:05 UTC, hoehna approved these changes
Yes, that looks much safer and cleaner.

2024-04-24 06:05 UTC, merged