Support Real _n_ in `rep(x, n)`
revbayes/revbayes pull request #587
Opened 2024-11-08 11:44 UTC by ms609

Closes #586 .

Allows
```rb
rep(1, 4 / 2)
rep(1, 2.0)
```

Previously these returned single-element vectors.

2024-11-08 14:16 UTC, ms609 commented
This Windows test failure is odd.  When I run the FBD tests locally on Win10 the files are created.  The GHA logs make it look like the files are created but not copied correctly.

2024-11-08 14:18 UTC, bredelings commented
Hmm.... it seems like the deeper problem is that RevBayes allows passing a Real to a Natural, but doesn't  convert it.

2024-11-08 14:21 UTC, bredelings commented
For example:
```
> _mod
   mod (Natural<any> x,
        Natural<any> y)
> _mod(2,5)
   2
> _mod(2.0,5)
   2
> _mod(4/2,5)
   2
```

2024-11-08 14:24 UTC, bredelings commented
Also apparently this work for me:
```
> rep(1, 4/2)
   [ 1, 1 ]
> rep(1, 2.0)
   [ 1, 1 ]
```

2024-11-08 16:07 UTC, ms609 commented
> Also apparently this work for me:
> 
> ```
> > rep(1, 4/2)
>    [ 1, 1 ]
> > rep(1, 2.0)
>    [ 1, 1 ]
> ```

Could this be because different OSs/architectures handle differently the cast to `int` in `(int)static_cast<const Natural &>( this->args[1].getVariable()->getRevObject() ).getValue();`?  I was surprised that reals all seem to get cast to `1` on my machine.  (I think from memory this was true under WSL as well as Windows?)

2024-11-08 16:09 UTC, ms609 commented
> I'm also curious what happens if you specify the argument names and if you give real numbers that aren't integers:


My guess is that the different behaviour reflects different cases that may or may not lead to calls to `ArgumentRule::fitArgument`.

2024-11-08 18:56 UTC, ms609 commented
On development branch, I saw the same output as you did.

2024-11-08 20:32 UTC, davidcerny reviewed
Hmm... to be honest, I don't necessarily see this as a good idea. The number of repetitions can only take natural numbers as meaningful values. In R, `rep(1, 2.5)` does apparently yield a vector of length 2, but in Python, `[1]*2.5` throws a type error (`can't multiply sequence by non-int of type 'float'`), and the latter seems like the correct behavior to me.

I agree that if `rep(1, 4/2)` and `rep(1, 2.0)` yield vectors of length 1 on Windows, that's an issue that's worth fixing, but IMO the fix shouldn't make it possible to also evaluate nonsensical expressions like `rep(1, 2.5)` or `rep(1, 5/2)`. I can also confirm that just like Ben, I'm getting the correct output for the first two of these expressions (i.e., `[ 1, 1 ]`) with the development branch on macOS. Getting rid of the inconsistent behavior on Windows vs. Unix is definitely worthwhile, but I'm not a big fan of rounding down `n` to the nearest integer.

2024-11-09 13:13 UTC, ms609 commented
If the intention is for users not to need to think about the types of their variables, I think it is important to support Real-typed variables. Insofar as the RevBayes philosophy is for a models to be explicitly specified, I can see a case for throwing an error on non integer Reals, perhaps pointing the user to call `ceiling` or `floor` for themselves.

2024-11-09 17:55 UTC, bredelings commented
Hmm... so there are a few cases:
- `rep(x, 4/2)`
- `rep(x,5/2)`
- `rep(x,sqrt(y))`
I kind of feel like the first one should work.  The second one, I'm not sure.  I feel like the third one should not work.

On the other hand, it seems like it would be better to implement a _general_ approach that converts `Real` to `Integer` if this is something good to do, instead of manually adding a second version of each function that takes an `Integer`.

I'm not sure this is the RevBayes philosophy, but moving away from implicit conversions seems like a good idea.  Especially loss type conversions like `5/2 -> 2`.  It has the unfortunately downside of making code more verbose though.

I guess in R all numbers are `Real`, so this doesn't come up.

2024-11-09 17:58 UTC, bredelings commented
Another idea would be to introduce a 'divide-and-floor' operator.  In R that is `%/%`.

2024-11-09 17:59 UTC, bredelings commented
https://search.r-project.org/CRAN/refmans/numbers/html/div.html\

Part of the issue is the standard `/` operator effectively works like `Integer x Integer -> Real`

2024-11-09 22:49 UTC, davidcerny commented
@ms609:

> I think it is important to support Real-typed integers. [...] I can see a case for throwing an error on non integer Reals, perhaps pointing the user to call `ceiling` or `floor` for themselves.

I agree with this 100%. I think maybe the goal of this PR should be to extend the current behavior on Unix (i.e., `rep(1, 4/2)` works but `rep(1, 5/2)` does not) to Windows as well.

@bredelings:

I don't see why `rep(x, sqrt(y))` shouldn't work as long as `sqrt(y)` evaluates to a natural number, which actually is the current behavior on Unix:

```
> y <- 9
> rep(1, sqrt(y))
   [ 1, 1, 1 ]
> y <- 8
> rep(1, sqrt(y))
   Error:	No overloaded function 'rep' matches for arguments ( Natural, RealPos )
```

In general, I think implicit conversions (i.e., weaker typing) can be a good thing as long as they are coupled with evaluation and checking. With this example, RevBayes (on Unix at least) is able to determine that `4/2` or `sqrt(9)` evaluates to a natural number (in which case it performs the appropriate conversion) but `5/2` and `sqrt(8)` do not (in which case it throws a type error). That seems like the right behavior to me. My problem with the type system is that it's inconsistent, and we can't rely on this desirable behavior across the board. For example, while `rep` evaluates (and if need be, converts) its `n` argument, `dnExp` doesn't do the same for its `lambda` argument, so `a <- 3.2 - 1.6; b ~ dnExp(1/a)` fails.

2024-11-11 14:11 UTC, ms609 commented
> On the other hand, it seems like it would be better to implement a _general_ approach that converts `Real` to `Integer` if this is something good to do, instead of manually adding a second version of each function that takes an `Integer`.

Agreed; ideally this would happen without the user thinking about it.  Presumably we would still need to register both function signatures in `RbRegister_*`.

For the meantime I've updated the code to fail on non-integer `Real` inputs, which I'm testing locally now before I push.  I want to include test cases to check that the 'fail' cases fail as anticipated; is there a mechanism for that?  I think if I just include the failures in `tests/.../replicate.Rev` the script will terminate at the first error.

2024-11-11 14:35 UTC, bredelings commented
I don't really like the approach of adding an overload with a Real argument.  I think that if the user wants a lossy type conversion they should use floor.

I think we should fix windows so that 4/2 works but 5/2 does not, the same as on UNIX.  Arguably we can/should add a message when trying to pass a Real to an Integer that this can be accomplished with `floor( )`.

2024-11-11 14:38 UTC, bredelings commented
> I don't see why rep(x, sqrt(y)) shouldn't work as long as sqrt(y) evaluates to a natural number, which actually is the current behavior on Unix:

This is the current behavior, and I'd lean against changing it.

However, if `y` is a deterministic node, then probably `sqrt(y)` evaluates to a natural number in some cases and not others. :man_shrugging:

2024-11-11 14:49 UTC, ms609 commented
#585 brought this to the surface; `rep` failed in a context like:

```rb
x <- 4          # x is an Integer
y <- x / 2      # silently converts x to a Real
rep(0, x)       # fails unexpectedly
```

Even now that I'm somewhat familiar with RevBayes, It certainly didn't strike me as intuitive that adding `floor` would fix this issue – or indeed that type conversion was relevant to the situation.

Perhaps there's a broader question here about how we communicate to the user what RevBayes is doing when types differ from the expected.  As a user, I've found it counterintuitive to have to use `abs()` to convince RevBayes that a `Real` I know to be positive is positive (coercing to `RealPos`); I'd find it similarly counterintuitive to use `floor` on a number I know to be an integer.  Sure, we can make the user do this themselves, and implement whatever checks are necessary – but it feels to me like a more straightforward user experience if RevBayes handles basic validation and supports valid input whatever the type.

2024-11-11 15:00 UTC, bredelings commented
```
> x <- 4
> y <- x/2
> rep(0,x)
   [ 0, 0, 0, 0 ]
```

This works?

2024-11-11 15:31 UTC, bredelings commented
I think it might be helpful to divide revbayes type issues into at least different classes.
1. crazy things that only revbayes does
2. non-crazy things that only revbayes does
3. things that some languages do that are not crazy

Change the type of `x` when you write `x/2` is in class 1 (rare, crazy).  Treating RealPos and Real as different types is in class 2 (rare, not crazy). Treating an Integer 4 different than a Real 4 is in class 3 (common, not crazy).  

A lot of languages require you to do explicit conversions to change types.  The question isn't if 4 is mathematically an integer.  The question is what bit representation is chosen to represent the 4.  And `Real` and `Integer` use different bit representations for the 4.  So arguably these are not the same thing.

In `C`, despite the fact that these things have different bit representations, you don't need to do explicit casting.  Sometimes this causes trouble.   For the example the following program:
```
#include <iostream>

int main()
{
    double z = 1e38;
    int a = z;
    unsigned b = z;
    long c = z;
    unsigned long d = z;
    std::cout<<"z = "<<z<<"   a = "<<a<<"  b = "<<b<<"  c = "<<c<<"  d = "<<d<<"\n";
}
```
compiles with no errors and produces the following output:
```
z = 1e+38   a = -2147483648  b = 0  c = -9223372036854775808  d = 0
```
Interestingly, when compiled with `-O3`, it gives different output:
```
z = 1e+38   a = 2147483647  b = 4294967295  c = 9223372036854775807  d = 18446744073709551615
```
In order to prevent crazy results like this, many languages force you to explicitly convert numeric types with different bit representations.

2024-11-11 16:42 UTC, ms609 commented
I agree that it's best to adopt a systematic approach to issues like this.  Since RevBayes likens itself to R (e.g. [here](https://revbayes.github.io/tutorials/intro/)] and many users are likely to be familiar with R syntax, I suspect that many RevBayes users will not be accustomed to thinking about types – besides other benefits, consistent behaviour when a type is 'incorrect' will help users to learn this distinction.  Also useful would be to direct users to clear documentation on how to manage types – for example, R has `as.integer`, so it took me a bit of thinking before I realised that `abs` could serve as `as.RealPos`.

2024-11-11 16:56 UTC, davidcerny commented
This is a great example of my [earlier complaint](https://davidcerny.github.io/post/teaching_revbayes/#fn:4) about Rev being strongly but implicitly typed. I think it would be completely fair to make the user think about the bit representation of a given value if the language was _explicitly_ typed, i.e., if it had type annotations:

```
Natural a <- 4
Real b <- 4
rep(1, a) # should work
rep(1, b) # should not
```

But because of design decisions that took place very early on, this is not the case. I guess we might eventually move in that direction a little bit by adding more function-style type casts along the lines of what we already have in `Probability()`: this was suggested in #414, and would help fix #308, for example.

However, for now, I tend to agree with @ms609 that the user is right to expect, say, integer values to behave as integers even if their underlying representation is different. If, in this particular case, this can be accomplished by adding an overload and checking the input, I'd be happy to approve.

2024-11-11 20:33 UTC, bredelings requested changes
I don't think that adding a new signature with a Real argument is the right approach.

Also, it seems like supplying `4/2` _already_ converts to an integer, so it also seems like this is unneeded?

2024-11-12 08:35 UTC, bjoelle commented
so from what I remember of my experiments with conversions, Rev currently supports converting `Real` to `Integer` if the conversion doesn't change the value (i.e. `2.0 -> 2` is (intended to be) possible but not `2.5 -> 2`)
at the moment this check is based on casting however (see `Real::convertTo`) which may be why there is OS-dependent weirdness

2024-11-12 08:41 UTC, bjoelle commented
also for added fun, note that the conversions will treat constant nodes differently than the others
the type changes only happen to constant nodes, other nodes will have a deterministic conversion node created

2024-11-12 17:29 UTC, davidcerny commented
Unfortunately, the latest commit doesn't preserve the desirable Unix behavior:

```
> rep(1, 5/2)
   [ 1, 1 ]
> rep(1, 2.5)
   [ 1, 1 ]
> y <- 8    
> rep(1, sqrt(y))
   [ 1, 1 ]
```

2024-11-12 17:48 UTC, davidcerny commented
@ms609 This looks very good, and preserves the desirable Unix behavior. I think that to make the tests pass, you just need to update the expected output?

2024-11-12 18:29 UTC, ms609 commented
I've done so, but the expected output only covers the tests that do not throw an error; once the first error is thrown, the script terminates, without verifying that the error is displayed as intended or that subsequent errors are observed.

2024-11-13 06:24 UTC, ms609 commented
As an imperfect workaround, I've created separate a test file for each error case; if an error is not thrown, this will overwrite the expected content in the output file.  This doesn't check that an error occurs for the anticipated reason, but is hopefully better than nothing.

2024-11-18 17:43 UTC, davidcerny commented
@ms609 Would you maybe like to push that workaround to see if the test runner can handle it? This PR is basically ready to be merged as far as I'm concerned; I'm happy to approve it as soon as it passes the tests.

The idea of a failing test producing a file where there should be none is interesting, and could be exploited elsewhere if it works.

2024-11-18 19:00 UTC, ms609 commented
Ah! Thanks for spotting that the push hadn't completed – I was pushing through WSL and didn't spot an error message.  Let's see what the test runner makes of the approach...

2024-11-18 20:29 UTC, davidcerny approved these changes
Works exactly as intended, and on top of that provides a very nice solution to the problem of testing for cases that are supposed to fail. Approving!

2024-11-19 08:50 UTC, ms609 commented
Great, thanks.  In `tests/run_integration_tests.sh`, I'm not sure what the purpose of checking for an `XFAIL` file in the test directory root would be – I wonder whether this was originally included in the preceding loop, or whether perhaps this is intended for developer use.  As it's not harmful, I'm inclined to leave it.

@bredelings are you satisfied that this now brings Windows behaviour in line with Unix, whilst retaining failure on inappropriate input?

2024-11-21 21:53 UTC, davidcerny commented
This is ready for (re-)review, I think.

2024-11-21 21:59 UTC, bredelings commented
> I don't think that adding a new signature with a Real argument is the right approach.
>
> Also, it seems like supplying 4/2 _already_ converts to an integer, so it also seems like this is unneeded?

I'm not sure I ever heard a response to the question here...  did I miss something?

2024-11-21 22:12 UTC, davidcerny commented
Since `rep(1, 4 / 2)` returns `[ 1 ]` on Windows according to the issue that this PR is trying to solve, it sounds like whatever conversion is currently taking place is not robust enough...

2024-11-21 22:22 UTC, bredelings commented
So shouldn't we find where that conversion is going wrong and fix it?

Additionally, `rep(1, 4 / 2)` returns `[1, 1]` when I run `rb.exe` under wine after compiling it for windows.  So that is confusing :-(

2024-11-22 07:35 UTC, ms609 commented
`rep(1, 4 / 2)`, and `rep(sqrt(4))`, do in fact return `[1, 1]` on Windows – I hadn't appreciated that these retained the integer type (as `type(4/2)` returns `RealPos`). `rep(1, 5 / 2)` throws a "no overloaded function" error.  

The initial motivation for this change was to handle a case where a number defined as an integer later had its type changed to a Real (#585).   I am in fact finding it difficult to construct an analogous failure case that doesn't rely on this behaviour.  This PR should nonetheless make us robust to equivalent cases, should they arise.

2024-11-22 14:13 UTC, davidcerny commented
I guess I'm getting a little confused. Is #586 basically a duplicate of #585 then? I.e. the problem is not with `rep()` at all, but with the unexpected and undesirable change of type?

2024-11-22 14:22 UTC, ms609 commented
I'm also feeling a bit confused, as I now can't reproduce the original behaviour from the script in #585 in either rb development or rb1.2.4, and I can't see why this would be the case.

2024-12-03 22:39 UTC, davidcerny commented
Since #586 has been closed, should we perhaps close this PR as well?

2024-12-03 23:19 UTC, closed without merging

2024-12-04 09:09 UTC, ms609 commented
I wonder whether it might be worth retaining the addition to documentation, and the test cases?

2024-12-04 21:10 UTC, davidcerny commented
That sounds like a good idea. If you want to open a new PR for these additions, I'll be happy to approve it.